In [1]:
import numpy as np
from sklearn.linear_model import LinearRegression

In [39]:
!pip install sklearn

In [84]:
x = np.array([5, 15, 25, 35, 45, 55]).reshape(-1, 1)
y = np.array([5, 20, 14, 32, 22, 38])

In [103]:
x

array([[ 5],
       [15],
       [25],
       [35],
       [45],
       [55]])

In [85]:
x.shape

(6, 1)

In [86]:
y

array([ 5, 20, 14, 32, 22, 38])

In [32]:
model = LinearRegression()

In [33]:
model.fit(x, y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [34]:
r_sq = model.score(x, y)

In [35]:
print('coefficient of determination:', r_sq)

coefficient of determination: 0.7158756137479542


In [93]:
type(model)

sklearn.linear_model.base.LinearRegression

In [36]:
print('intercept:', model.intercept_)

intercept: 5.633333333333329


In [37]:
print('slope:', model.coef_)

slope: [0.54]


In [38]:
y_pred = model.predict(x)

In [15]:
print('predicted response:', y_pred, sep='\n')

predicted response:
[ 8.33333333 13.73333333 19.13333333 24.53333333 29.93333333 35.33333333]


In [16]:
y_pred = model.intercept_ + model.coef_ * x

In [98]:
mean_squared_error(y, y_pred)

33.75555555555555

In [17]:
print('predicted response:', y_pred, sep='\n')

predicted response:
[[ 8.33333333]
 [13.73333333]
 [19.13333333]
 [24.53333333]
 [29.93333333]
 [35.33333333]]


In [19]:
#In practice, regression models are often applied for forecasts. 
#This means that you can use fitted models to calculate the outputs based on some other, new inputs:

In [20]:
x_new = np.arange(5).reshape((-1, 1))

In [21]:
print(x_new)

[[0]
 [1]
 [2]
 [3]
 [4]]


In [22]:
y_new = model.predict(x_new)

In [23]:
print(y_new)

[5.63333333 6.17333333 6.71333333 7.25333333 7.79333333]


In [24]:
#Here .predict() is applied to the new regressor x_new and yields the response y_new. 
#This example conveniently uses arange() from numpy to generate an array with the elements from 0 (inclusive) to 5 (exclusive), that is 0, 1, 2, 3, and 4.